apiVersion: v1
kind: Service
metadata:
  name: dataeng-nginx-service
  labels:
    app: dataeng
spec:
  type: NodePort
  selector:
    app: dataeng
  ports:
  - name: web
    port: 80
    nodePort: 30001