apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataeng-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataeng
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dataeng
    spec:
      containers:
      - name: nginx
        # image: localhost:5001/nginx:dataeng
        image: nginx
        ports:
        - containerPort: 80
      #   volumeMounts:
      #     - name: conf
      #       mountPath: /etc/nginx/nginx.conf
      #       subPath: nginx.conf
      #     - name: confd
      #       mountPath: /etc/nginx/conf.d/dataeng.conf
      #     - name: html
      #       mountPath: /var/www/html
      # volumes:
      #   - name: conf
      #     hostPath:
      #       path: /Users/muhammadandriyan/Documents/development/docker/la-story-telling/conf
      #   - name: confd
      #     hostPath:
      #       path: /Users/muhammadandriyan/Documents/development/docker/la-story-telling/conf/conf.d/dataeng.conf
      #   - name: html
      #     hostPath:
      #       path: /Users/muhammadandriyan/Documents/development/docker/la-story-telling/html